### ISSUE TITLE
1.0.0-beta.6: [ERROR] Could not resolve "../index" (Nuxt v3.1.2)

### ISSUE THREAD

**Issue by bikalpabhurtel** [formkit/auto-animate#123]
This problem occurred after updating to the latest version of nuxt from 3.1.1 to 3.1.2. It was working properly in 3.1.1. Similar issue was reported in https://github.com/formkit/auto-animate/issues/73 for @formkit/auto-animate^1.0.0-beta.2. 

    Nuxi 3.1.2                                                                17:48:47
    Nuxt 3.1.2 with Nitro 2.1.2  

    > Local:    http://localhost:3000/ 

    ✔ Nitro built in 5736 ms                                                  nitro 17:49:13
    ✘ [ERROR] Could not resolve "../index"

    node_modules/@formkit/auto-animate/vue/index.mjs:1:29:
      1 │ import { vAutoAnimate } from '../index';
        ╵                              ~~~~~~~~~~

    ERROR  5:49:16 PM [vite] error while updating dependencies:      17:49:16    
    Error: Build failed with 1 error:
    node_modules/@formkit/auto-animate/vue/index.mjs:1:29: ERROR: Could not resolve "../index"
        at failureErrorWithLog (/home/bikalpa/Desktop/***/***/***/node_modules/vite/node_modules/esbuild/lib/main.js:1604:15)
        at /home/bikalpa/Desktop/***/***/***/node_modules/vite/node_modules/esbuild/lib/main.js:1056:28
        at runOnEndCallbacks (/home/bikalpa/Desktop/***/***/***/node_modules/vite/node_modules/esbuild/lib/main.js:1476:61)
        at buildResponseToResult (/home/bikalpa/Desktop/***/***/***/node_modules/vite/node_modules/esbuild/lib/main.js:1054:7)
        at /home/bikalpa/Desktop/***/***/***/node_modules/vite/node_modules/esbuild/lib/main.js:1166:14
        at responseCallbacks.<computed> (/home/bikalpa/Desktop/***/***/***/node_modules/vite/node_modules/esbuild/lib/main.js:701:9)
        at handleIncomingPacket (/home/bikalpa/Desktop/***/***/***/node_modules/vite/node_modules/esbuild/lib/main.js:756:9)
        at Socket.readFromStdout (/home/bikalpa/Desktop/***/***/***/node_modules/vite/node_modules/esbuild/lib/main.js:677:7)
        at Socket.emit (node:events:513:28)
        at Socket.emit (node:domain:489:12)

**Comment by justin-schroeder** [comment]
Is this issue still persisting in Nuxt 3.2.2 @bikalpabhurtel

**Comment by MrThursby** [comment]
Nuxt 3.4.2 - same problem..

The problem only occurs when using yarn.. If I use npm, it works well.

**Comment by MrThursby** [comment]
I rolled back nuxt to version 3.1.1, but the problem remained..

**Comment by fahdlaabi** [comment]
Nuxt 3.6.0 - same problem

**Comment by LehuyH** [comment]
Still happening. 

Changing .`./index` import to `../index.mjs"`
fixes this issue
