### ISSUE TITLE
No "exports" main defined error when running tests

### ISSUE THREAD

**Issue by satueveliina** [formkit/auto-animate#35]
Hi! Nice package! 

I encountered an issue when running the tests. It works perfectly fine in local development but fails when running tests with mocha  with the following error. Any help is appreciated on how to get around this. 

Mocha version is ^6.2.0 and Typescript is 4.5. 

```
> NODE_PATH=. mocha --exit --timeout 10000 --require ts-node/register --reporter spec $(npm run --silent test-frontend-list)

node: v14.18.0
npm: v6.14.15
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in  .../node_modules/@formkit/auto-animate/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:511:7)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> ... /frontend/ui/utils/AnimationContainer.tsx:2:1)
```
Here's the import which is causing the error:
```
import autoAnimate from '@formkit/auto-animate';
```

 tsconfig.json:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "jsx": "react",
    "baseUrl": ".",
    "allowSyntheticDefaultImports": true,
    "noErrorTruncation": true,
    "lib": ["es2015", "es2016.array.include", "dom", "es2018.promise"],
    "allowJs": true,
    "noUnusedParameters": false,
    "noUnusedLocals": false,
    "strictPropertyInitialization": false,
    "noImplicitAny": true,
    "strictNullChecks": true
  }
}
```

**Comment by justin-schroeder** [comment]
This is an ESM only package, and we're unlikely to provide CJS support. Upgrade your tooling and it should be good to go.
