### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED error with vite.

### ISSUE THREAD

**Issue by dbousamra** [formkit/auto-animate#42]
Fresh install, 1.0.0-beta.1

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './react' is not defined by "exports" in /Users/blah/Code/Projects/piccolo/piccolo-web/node_modules/@formkit/auto-animate/package.json
@piccolohealth/web-server:     at new NodeError (internal/errors.js:322:7)
@piccolohealth/web-server:     at throwExportsNotFound (internal/modules/esm/resolve.js:332:9)
@piccolohealth/web-server:     at packageExportsResolve (internal/modules/esm/resolve.js:523:7)
@piccolohealth/web-server:     at resolveExports (internal/modules/cjs/loader.js:450:36)
@piccolohealth/web-server:     at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
@piccolohealth/web-server:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
@piccolohealth/web-server:     at Function.Module._resolveFilename (/Users/dbousamra/Code/Projects/piccolo/piccolo-web/node_modules/tsconfig-paths/lib/register.js:75:40)
@piccolohealth/web-server:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
@piccolohealth/web-server:     at Module.require (internal/modules/cjs/loader.js:974:19)
@piccolohealth/web-server:     at require (internal/modules/cjs/helpers.js:101:18)
@piccolohealth/web-server:     at Object.<anonymous> (/Users/dbousamra/Code/Projects/piccolo/piccolo-web/packages/client/src/hooks/useAnimate.ts:2:1)
@piccolohealth/web-server:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
@piccolohealth/web-server:     at Module._compile (/Users/dbousamra/Code/Projects/piccolo/piccolo-web/node_modules/source-map-support/source-map-support.js:547:25)
@piccolohealth/web-server:     at Module.m._compile (/private/var/folders/vb/cgx9vs8x6tv9154qvqqcqgnw0000gp/T/ts-node-dev-hook-5126279500872808.js:69:33)
@piccolohealth/web-server:     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
@piccolohealth/web-server:     at require.extensions.<computed> (/private/var/folders/vb/cgx9vs8x6tv9154qvqqcqgnw0000gp/T/ts-node-dev-hook-5126279500872808.js:71:20)
@piccolohealth/web-server:     at Object.nodeDevHook [as .ts] (/Users/dbousamra/Code/Projects/piccolo/piccolo-web/node_modules/ts-node-dev/lib/hook.js:63:13)
@piccolohealth/web-server:     at Module.load (internal/modules/cjs/loader.js:950:32)
@piccolohealth/web-server:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
@piccolohealth/web-server:     at Module.require (internal/modules/cjs/loader.js:974:19)
@piccolohealth/web-server:     at require (internal/modules/cjs/helpers.js:101:18)
@piccolohealth/web-server:     at Object.<anonymous> (/Users/dbousamra/Code/Projects/piccolo/piccolo-web/packages/client/src/components/templates/statements/manager/SortableStatementTemplates.tsx:17:1)
@piccolohealth/web-server: [ERROR] 19:19:41 Error: Package subpath './react' is not defined by "exports" in /Users/dbousamra/Code/Projects/piccolo/piccolo-web/node_modules/@formkit/auto-animate/package.json
```

**Comment by justin-schroeder** [comment]
Thanks, can you provide what this is a fresh install of? Would you mind providing a minimal reproduction so we can trace this ourselves? That would be super helpful. Thank you!
