### ISSUE TITLE
1.0.0-beta.2: [ERROR] Could not resolve "../index" (Nuxt v3.0.0-rc.8)

### ISSUE THREAD

**Issue by mblachlov24** [formkit/auto-animate#73]
Nuxt CLI v3.0.0-rc.8.
I will add that everything worked fine in the 1.0.0-beta.1 version.

```node
Nuxt CLI v3.0.0-rc.8                                                                       20:15:02
                                                                                           20:15:14
  > Local:    http://localhost:3000/ 
  > Network:  http://localhost:3000/

ℹ Vite server warmed up in 665ms                                                           20:15:16
✘ [ERROR] Could not resolve "../index"

    node_modules/@formkit/auto-animate/vue/index.mjs:2:42:
      2 │ import autoAnimate, { vAutoAnimate } from '../index';
        ╵                                           ~~~~~~~~~~


 ERROR  8:15:17 PM [vite] error while updating dependencies:                               20:15:17
Error: Build failed with 1 error:
node_modules/@formkit/auto-animate/vue/index.mjs:2:42: ERROR: Could not resolve "../index"
    at failureErrorWithLog (/home/nuxt-app/node_modules/vite/node_modules/esbuild/lib/main.js:1624:15)
    at /home/nuxt-app/node_modules/vite/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/home/nuxt-app/node_modules/vite/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/home/nuxt-app/node_modules/vite/node_modules/esbuild/lib/main.js:1264:7)
    at /home/nuxt-app/node_modules/vite/node_modules/esbuild/lib/main.js:1377:14
    at /home/nuxt-app/node_modules/vite/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/home/nuxt-app/node_modules/vite/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/home/nuxt-app/node_modules/vite/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
```

**Comment by rromanv** [comment]
Same issue but not nuxt, VITE v3.0.9

**Comment by productdevbook** [comment]
some vue 3 + vite problem

**Comment by justin-schroeder** [comment]
Just publish a hotfix beta.3 that should resolve this regression.
