### ISSUE TITLE
1.0.0-beta.2 Build Error on Vite(with Vue)

### ISSUE THREAD

**Issue by nirnejak** [formkit/auto-animate#74]
Getting the following error when trying to start development server

**auto-animate** - 1.0.0-beta.2
**vite** - 3.0.9

```bash
node_modules/@formkit/auto-animate/vue/index.mjs:2:42:
      2 │ import autoAnimate, { vAutoAnimate } from '../index';
        ╵                                           ~~~~~~~~~~

/Users/nirnejak/Code/draxlr-frontend/node_modules/esbuild/lib/main.js:1605
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/@formkit/auto-animate/vue/index.mjs:2:42: ERROR: Could not resolve "../index"
    at failureErrorWithLog (/Users/nirnejak/Code/draxlr-frontend/node_modules/esbuild/lib/main.js:1605:15)
    at /Users/nirnejak/Code/draxlr-frontend/node_modules/esbuild/lib/main.js:1251:28
    at runOnEndCallbacks (/Users/nirnejak/Code/draxlr-frontend/node_modules/esbuild/lib/main.js:1034:63)
    at buildResponseToResult (/Users/nirnejak/Code/draxlr-frontend/node_modules/esbuild/lib/main.js:1249:7)
    at /Users/nirnejak/Code/draxlr-frontend/node_modules/esbuild/lib/main.js:1358:14
    at /Users/nirnejak/Code/draxlr-frontend/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/Users/nirnejak/Code/draxlr-frontend/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/Users/nirnejak/Code/draxlr-frontend/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 42,
        file: 'node_modules/@formkit/auto-animate/vue/index.mjs',
        length: 10,
        line: 2,
        lineText: "import autoAnimate, { vAutoAnimate } from '../index';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
```

**Comment by justin-schroeder** [comment]
Just publish a hotfix beta.3 that should resolve this regression.
